224 FEAT: Add function to get swap path by type
yozh-io/1inch-widget pull request #296
Opened 2022-12-29 16:04 UTC by setrix422

2022-12-29 18:20 UTC, AlinaYozh requested changes

2022-12-29 18:20 UTC, AlinaYozh commented on src/services/joeRouter.ts
> +    [SwapAvalancheType.swapExactAVAXForTokens]: [fromTokenAddress, WAVAX, toTokenAddress],
Incorrect type name - this type is correct where [WAVAX, tokenAddress] . Array with 3 addresses should have type **ExactTokenToToken**. 

That was described in the [task](https://github.com/yozh-io/1inch-widget/issues/224)

2022-12-29 18:26 UTC, setrix422 commented on src/services/joeRouter.ts
> +    [SwapAvalancheType.swapExactAVAXForTokens]: [fromTokenAddress, WAVAX, toTokenAddress],
So, to double check, in case ExactTokenToToken we need to return array with token instances?

2022-12-29 18:53 UTC, AlinaYozh commented on src/services/joeRouter.ts
> +    [SwapAvalancheType.swapExactAVAXForTokens]: [fromTokenAddress, WAVAX, toTokenAddress],
**The mistake is - type swapExactAVAXForTokens is used twice** 

In all cases need to return an array.

Joe router is modified uniswap v2 router, so we can use uniswap docs:

> Swaps an exact amount of input tokens for as many output tokens as possible, along the route determined by the path. The first element of path is the input token, the last is the output token, and any intermediate elements represent intermediate pairs to trade through (if, for example, a direct pair does not exist).

Links:

- [TokensForTokens](https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-02#swapexacttokensfortokens)
- [EthForTokens](https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-02#swapexactethfortokens)
- [TokensForEth](https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-02#swaptokensforexacteth)

2022-12-29 18:58 UTC, setrix422 commented on src/services/joeRouter.ts
> +    [SwapAvalancheType.swapExactAVAXForTokens]: [fromTokenAddress, WAVAX, toTokenAddress],
Oh, sure, got it)

2022-12-29 19:08 UTC, AlinaYozh reviewed
<img width="1216" alt="Screenshot 2022-12-29 at 23 07 15" src="https://user-images.githubusercontent.com/80710083/209997867-4577c30c-cee1-4997-9258-fbd411039e0c.png">

2022-12-29 19:42 UTC, setrix422 commented
Error with module absence will be fixed after pr on [https://github.com/yozh-io/1inch-widget/issues/222](issue) will be merged

2022-12-30 10:48 UTC, Richardowsky approved these changes

2022-12-30 11:00 UTC, heimlee commented on src/services/joeRouter.ts
> +  const { fromToken, toToken }: { fromToken: Token; toToken: Token } = useAppSelector((state) => ({
When calling getSwapPath function, there will be such error with useAppSelector hook:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/43527919/210062691-0169b3fa-45f5-4486-b8ee-57f2a8fde28e.png">

2022-12-30 16:28 UTC, setrix422 commented on src/services/joeRouter.ts
> +  const { fromToken, toToken }: { fromToken: Token; toToken: Token } = useAppSelector((state) => ({
Token instances have been moved  to method params

2022-12-31 03:17 UTC, merged