223 FEAT: Add JR Swap, Add JR Quote
yozh-io/1inch-widget pull request #300
Opened 2023-01-14 14:19 UTC by setrix422

Added: 
1) JoeRouter swap methods
2) JoeRouter quote
Changed:
1) JoeRouter Constructor argument(provider) changed to signerOrProvider
2) getSwapAvalanchePath type(string[] | error) changed to string[]

2023-01-16 07:30 UTC, heimlee requested changes

2023-01-16 07:48 UTC, AlinaYozh requested changes

2023-01-16 07:48 UTC, AlinaYozh commented on src/hooks/update/useUpdate.ts
>            // { name: ProtocolName.UNISWAP_V3, update: () => uniswapUpdater(params) },
 Is uniswap_v3 should be commented? 🤔

2023-01-16 07:48 UTC, AlinaYozh commented on src/hooks/update/useUpdateJoeRouterQuote.ts
> +  }, []);
why dependencies are empty?

2023-01-16 07:48 UTC, AlinaYozh commented on src/services/joeRouter.ts
> +  const JoeRouterContract = JoeRouter(signer);
should be signerOrProvider. Signer can be unavailable

2023-01-16 07:48 UTC, AlinaYozh commented on src/services/joeRouter.ts
> +export const getJoeRouterSwap = async (params: UpdateQuoteParams) => {
do not use params! To get swap you use `fromToken, toToken, amountIn and provider`. It can be shown directly

2023-01-16 07:48 UTC, AlinaYozh commented on src/services/swap/buildJoeRouterTx.ts
> +      from: String(params.fromAddress),
address is always a string

2023-01-16 07:53 UTC, setrix422 commented on src/services/joeRouter.ts
> +  const JoeRouterContract = JoeRouter(signer);
joeRouter swap method requiers Singer

2023-01-16 07:57 UTC, setrix422 commented on src/services/swap/buildJoeRouterTx.ts
> +      from: String(params.fromAddress),
Uniswap v3 has the same ref, but OK

2023-01-16 08:13 UTC, setrix422 commented on src/services/joeRouter.ts
> +export const getJoeRouterSwap = async (params: UpdateQuoteParams) => {
Creating token instances requiers 6 strings of code, function is called in two different places, should it duplicate code and pass args directly or just creating local with params?

2023-01-16 08:52 UTC, AlinaYozh commented on src/services/swap/buildJoeRouterTx.ts
> +      from: String(params.fromAddress),
mistakes can be, but we need to fix it

2023-01-17 11:09 UTC, heimlee approved these changes

2023-01-17 11:16 UTC, AlinaYozh approved these changes

2023-01-17 11:18 UTC, Richardowsky approved these changes

2023-01-17 11:18 UTC, merged