310/311 [Joe Sdk] The best route on "Routes" modal
yozh-io/1inch-widget pull request #320
Opened 2023-01-24 10:40 UTC by heimlee

2023-01-27 09:45 UTC, setrix422 commented on src/utils/getPoolFeePercentForStep.ts
> +  const denominator = '1000000000000000';
Why using exactly '1000000000000000'?

2023-01-27 09:54 UTC, heimlee commented on src/utils/getPoolFeePercentForStep.ts
> +  const denominator = '1000000000000000';
Because we get a big value from quote.fees ([LBQuoter contract](https://github.com/traderjoe-xyz/joe-v2/blob/07f10212e2de6abc97932240c27388c14868582c/src/LBQuoter.sol#L118))

2023-01-27 10:03 UTC, setrix422 commented on src/utils/getPoolFeePercentForStep.ts
> +  const denominator = '1000000000000000';
It looks like quote.fees returns number(1e18) bigger than 1000000000000000
![image](https://user-images.githubusercontent.com/88155740/215059853-23b960dd-2cc5-4820-b610-a41f54f024ac.png)

2023-01-27 10:06 UTC, setrix422 commented on src/utils/getPoolFeePercentForStep.ts
> +  const denominator = '1000000000000000';
So, in case of [fees](https://github.com/traderjoe-xyz/joe-v2/blob/07f10212e2de6abc97932240c27388c14868582c/src/LBQuoter.sol#L118) === 1, poolFeePercentPerStep will be equal to 1*1e18/'1000000000000000' = 1000%

2023-01-27 10:28 UTC, heimlee commented on src/utils/getPoolFeePercentForStep.ts
> +  const denominator = '1000000000000000';
fixed https://github.com/yozh-io/1inch-widget/pull/320/commits/4da75737df48d4ef6349d65c2e55b052d4f126a1

2023-01-27 10:44 UTC, setrix422 approved these changes

2023-01-27 14:07 UTC, setrix422 approved these changes

2023-01-30 14:07 UTC, AlinaYozh requested changes

2023-01-30 14:07 UTC, AlinaYozh commented on src/utils/getUniswapTokenPath.ts
> + */
It's a comment - not js doc
```ts
/**
* @function
* @description Returns an array of Uniswap routing diagram entries for a trade.
* @param {Trade<Currency, Currency, TradeType>} trade - A trade object with input and output amount * information.
* @returns {UniswapRoutingDiagramEntry[]} - An array of Uniswap routing diagram entries for the trade.
*/
```
also we can describe property like:
```ts
@property {Currency} inputAmount - The input amount.
@property {Currency} outputAmount - The output amount.
@property {Array<Array<Currency|number>>} path - The token path with fee information.
```

2023-01-30 16:59 UTC, AlinaYozh commented on src/utils/getPoolFeePercentForStep.ts
> +  );
**UPD:**
```ts
const base = new BigNumber(10).pow(18); // 10^18

/**
 * Calculates the pool fee percentage for each step of the swap
 * 
 * @param {BigNumber[]} fees - An array of BigNumber objects representing the fees for each step of the swap
 * 
 * @returns {number[]} An array of numbers representing the pool fee percentage for each step of the swap
 */
export const getPoolFeePercentForStep = (fees: BigNumber[]): number[] => {
  return fees.map((bn: BigNumber) =>
    new Percent(bn, base).decimal.toNumber()
  );
```

2023-01-30 18:51 UTC, AlinaYozh commented on src/utils/getPoolFeePercentForStep.ts
> +  );
@heimlee add unit tests

```ts
const base = new BigNumber(10).pow(18);

describe('getPoolFeePercentForStep', () => {
  it('should return the correct pool fee percentage for each step', () => {
    const fees = [
      new BigNumber(500000000000000000),
      new BigNumber(1000000000000000000),
      new BigNumber(1500000000000000000)
    ];

    expect(getPoolFeePercentForStep(fees)).toEqual([0.5, 1, 1.5]);
  });

  it('should return an array of 0 if all fees are 0', () => {
    const fees = [new BigNumber(0), new BigNumber(0), new BigNumber(0)];

    expect(getPoolFeePercentForStep(fees)).toEqual([0, 0, 0]);
  });

  it('should return an empty array if the fees parameter is an empty array', () => {
    expect(getPoolFeePercentForStep([])).toEqual([]);
  });

  it('should return an empty array if the fees parameter is not an array of BigNumber objects', () => {
    expect(getPoolFeePercentForStep(null)).toEqual([]);
    expect(getPoolFeePercentForStep([])).toEqual([]);
    expect(getPoolFeePercentForStep([1, 2, 3])).toEqual([]);
  });
});
```

2023-01-31 07:36 UTC, heimlee commented on src/utils/getPoolFeePercentForStep.ts
> +  );
Fixed https://github.com/yozh-io/1inch-widget/pull/320/commits/1a3830460ddb580e7831237dbd8681a696eb01c0.
I used `BigNumber.from()` to create BN instead of `new BigNumber` because it was impossible to create BN in this way.

2023-01-31 07:37 UTC, heimlee commented on src/utils/getJoeRouterTokenPath.ts
> +  } = trade;
Fixed https://github.com/yozh-io/1inch-widget/pull/320/commits/910c5d958750acb91d1de9be1fc1682ac8900da9

2023-01-31 07:37 UTC, heimlee commented on src/utils/getJoeRouterTokenPath.ts
> +  }
Fixed https://github.com/yozh-io/1inch-widget/pull/320/commits/910c5d958750acb91d1de9be1fc1682ac8900da9

2023-01-31 07:37 UTC, heimlee commented on src/utils/getUniswapTokenPath.ts
> + */
Fixed https://github.com/yozh-io/1inch-widget/pull/320/commits/a648b0177321018d06b28ac540fc8487c55c57fb

2023-01-31 19:24 UTC, AlinaYozh approved these changes

2023-01-31 19:25 UTC, merged